# Generated by Django 3.0 on 2022-10-13 15:48
from django.apps import apps as global_apps
from django.db import migrations
from django.contrib.auth.models import User


def forwards(apps, schema_editor):
    try:
        old_profile_model = apps.get_model('oc_lettings_site', 'Profile')
    except LookupError:
        # The old app isn't installed.
        return

    new_profile_model = apps.get_model('profiles', 'Profile')
    objs = [
        new_profile_model(
            user=old_profile_instance.user,
            favorite_city=old_profile_instance.favorite_city,
        ) for old_profile_instance in old_profile_model.objects.all()
    ]
    new_profile_model.objects.bulk_create(objs=objs)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0002_auto_20221012_1745'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0002_auto_20221012_1745'))
