# Generated by Django 3.0 on 2022-10-13 08:37
from django.apps import apps as global_apps
from django.db import migrations


def forwards(apps, schema_editor):
    try:
        old_address_model = apps.get_model('oc_lettings_site', 'Address')
    except LookupError:
        # The old app isn't installed.
        return

    new_adresse_model = apps.get_model('lettings', 'Address')
    objs = [
        new_adresse_model(
            number=old_address_instance.number,
            street=old_address_instance.street,
            city=old_address_instance.city,
            state=old_address_instance.state,
            zip_code=old_address_instance.zip_code,
            country_iso_code=old_address_instance.country_iso_code,
        ) for old_address_instance in old_address_model.objects.all()
    ]
    new_adresse_model.objects.bulk_create(objs=objs)


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0002_auto_20221012_1745'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0002_auto_20221012_1745'))
