version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test: # name of the job
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run pytest
          command: python -m pytest
      - run:
          name: Run flake8
          command: python -m flake8
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.9.4
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build and Push docker image
          command: |
            TAG=$CIRCLE_SHA1
            docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$TAG .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$TAG

  deploy_heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Log and push to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web

workflows:
  default:
    jobs:
      - build_and_test
      - build_and_push_docker_image:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
      - deploy_heroku:
          requires:
            - build_and_push_docker_image
          filters:
            branches:
              only:
                - master
