version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test: # name of the job
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run pytest
          command: python -m pytest
      - run:
          name: Run flake8
          command: python -m flake8
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.9.4
        auth:
          username: edaucohe
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build and Push docker image
          command: |
            TAG=$CIRCLE_SHA1
            docker build -t edaucohe/lettings:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u edaucohe --password-stdin
            docker push edaucohe/lettings:$TAG

  run_test:
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout
      - run:
          name: pytest
          command: |
            docker run $DOCKER_REPOSITORY/$CIRCLE_SHA1 pytest

  ensure_quality:
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout
      - run:
          name: flake8
          command: |
            docker run $DOCKER_REPOSITORY/$CIRCLE_SHA1 flake8

workflows:
  default:
    jobs:
      - build_and_push_docker_image
      - run_test:
          requires:
            - build_and_push_docker_image
          filters:
            branches:
              only:
                - master
      - ensure_quality:
          requires:
            - build_and_push_docker_image
          filters:
            branches:
              only:
                - master
