version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test: # name of the job
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run pytest
          command: python -m pytest
      - run:
          name: Run flake8
          command: python -m flake8
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_docker_image:
    docker:
      - image: cimg/python:3.9.4
        auth:
          username: edaucohe
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run:
          name: Build and Push docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t edaucohe/lettings:latest .
            echo $DOCKER_PASS | docker login -u edaucohe --password-stdin
            docker push edaucohe/lettings:latest

workflows:
  test_docker_deploy:
    jobs:
      - build_and_test
      - build_docker_image:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
